name: Test Rohit
favicon: null
layout_spectrum: 0.7719882917590439
typography_spectrum: 0.9469177073333412
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08393795089796185
  lightness: 0.3983425891492516
  saturation: 0.925407325848937
  rhythmicContrast: 0.06762486533261836
purpose: []
